# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [1]:
# Your code here
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df= pd.read_csv(url)

In [3]:
print(f"Dataset dimensions :{df.shape} (rows,columns)")

Dataset dimensions :(4008, 11) (rows,columns)

In [4]:
df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [10]:
print("\n Unique values per column: ")
for col in df.columns:
    unique_count =df[col].nunique()
    print(f"{col}:{unique_count} unique values")
    if unique_count < 10:
        print(f"unique values: {df[col].unique()}")
    elif pd.api.types.is_numeric_dtype(df[col]):
            print(f" Range:{df[col].min()} to {df[col].max()}")

 Unique values per column:
Customer:1071 unique values
ST:8 unique values
unique values: ['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'Cali' 'AZ' 'WA'
 nan]
GENDER:5 unique values
unique values: [nan 'F' 'M' 'Femal' 'Male' 'female']
Education:6 unique values
unique values: ['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor'
 nan]
Customer Lifetime Value:1027 unique values
Income:774 unique values
 Range:0.0 to 99960.0
Monthly Premium Auto:132 unique values
 Range:61.0 to 35354.0
Number of Open Complaints:6 unique values
unique values: ['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]
Policy Type:3 unique values
unique values: ['Personal Auto' 'Corporate Auto' 'Special Auto' nan]
Vehicle Class:6 unique values
unique values: ['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car' nan]
Total Claim Amount:761 unique values
 Range:0.382107 to 2893.239678

In [11]:
df.describe()

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [13]:
df.describe(include=['object'])

,Customer,ST,GENDER,Education,Customer Lifetime Value,Number of Open Complaints,Policy Type,Vehicle Class
count,1071,1071,954,1071,1068,1071,1071,1071
unique,1071,8,5,6,1027,6,3,6
top,RB50392,Oregon,F,Bachelor,445811.34%,1/0/00,Personal Auto,Four-Door Car
freq,1,320,457,324,4,830,780,576

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [16]:
# Your code here
location_counts = df['ST'].value_counts()
top5_least_common =location_counts.nsmallest(5)
print("Top 5 least common customer location: ")
print(top5_least_common)

Top 5 least common customer location:
ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [19]:
# Your code here
policy_counts =df['Policy Type'].value_counts()
most_common_policy =policy_counts.idxmax()
print(f"\n Policy type with highest sales : {most_common_policy}")
print(f"Number sold : {policy_counts.max()}")

 Policy type with highest sales : Personal Auto
Number sold : 780

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [22]:
# Your code here
personal_auto = df.loc[df['Policy Type'] == 'Personal Auto']
corporate_auto = df.loc[df['Policy Type'] == 'Corporate Auto']

avg_income_personal = personal_auto['Income'].mean()
avg_income_corporate = corporate_auto['Income'].mean()
print(f"\n Average income for personal auto policies: $ {avg_income_personal:,.2f}")
print(f"\n Average income for corporate auto policies: ${avg_income_corporate:,.2f}")

 Average income for personal auto policies: $ 38,180.70

 Average income for corporate auto policies: $41,390.31

In [23]:
if avg_income_personal < avg_income_corporate:
    print("Customers with personal auto policeis have lower income than corporate auto customers")
elif avg_income_personal > avg_income_corporate:
    print("Customers with personal auto policies have higher income than corporate auto customers")
else:
    print("Both policy types have customers with similar average income.")

Customers with personal auto policeis have lower income than corporate auto customers

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
# Your code here